name: Docker Publish

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: luismachadoreis/heimdall-server
          tags: |
            type=raw,value=latest
            type=raw,value=${{ github.ref_name }}
            type=raw,value=${{ github.sha }}
            type=raw,value=${{ github.ref_name }}-${{ github.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            luismachadoreis/heimdall-server:latest
            luismachadoreis/heimdall-server:${{ env.VERSION }}
            luismachadoreis/heimdall-server:${{ env.VERSION }}-${{ github.sha }}
            luismachadoreis/heimdall-server:${{ github.sha }} 