name: Docker Publish

on:
  # workflow_run:
  #   workflows: ["CI"]
  #   types:
  #     - completed
  #   branches:
  #     - main
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    # if: |
    #   github.event.workflow_run.conclusion == 'success' &&
    #   startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: luismachadoreis/heimdall-server
          tags: |
            type=raw,value=latest
            type=raw,value=${{ github.ref_name }}
            type=raw,value=${{ env.SHORT_SHA }}
            type=raw,value=${{ github.ref_name }}-${{ env.SHORT_SHA }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Set short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./heimdall-server
          push: true
          build-args: |
            GITHUB_TOKEN=${{ secrets.GH_PACKAGES_TOKEN }}
          tags: |
            luismachadoreis/heimdall-server:latest
            luismachadoreis/heimdall-server:${{ env.VERSION }}
            luismachadoreis/heimdall-server:${{ env.VERSION }}-${{ env.SHORT_SHA }}
            luismachadoreis/heimdall-server:${{ env.SHORT_SHA }} 